
services:
  mysql:  
    image: mysql:8  
    container_name: mysql_db  
    environment:  
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_PASSWORD: 1111
    ports:
      - "80:3306"  # Пробрасываем порт корректно

  app:  
    build: .
    container_name: python_parser  
    depends_on:  
      - mysql
    environment:
      PYTHONPATH: /usr/src  # Добавляем переменную окружения
